person= input("Enter a Person: ")
verb1 = input("Enter a verb: ")
adj = input("Enter a adjective: ")
noun = input("Enter a noun: ")
verb2 = input("Enter a verb: ")
number = input("Enter a number: ")
house = input("Enter a household item: ")
location = input("Enter a location: ")
print(person + " " + verb1 + " "  + adj + " through the " + noun + ".")
print("They " + verb2 + " into " + number + " of " + location + ".")